version: '3'

services:
  backend: 
    image: tournament-test
    container_name: tournament-test
    build: 
      context: .
      dockerfile: '.docker/Dockerfile'
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - tournament-ingress 
  dynamoDB: 
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8001:8001"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      tournament-ingress:
        ipv4_address: 12.5.0.1

networks: 
  tournament-ingress:
    driver: bridge
    ipam:
      config:
        - subnet: 12.5.0.0/16